services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d myappdb","curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - postgres
    ports:
      - "5050:80" # Expose PgAdmin on port 5050 of the host
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network

  fastapi:
    build: .
    volumes:
      - ./:/myapp/
    depends_on:
      - postgres
      - minio
    environment:
      PYTHONPATH: /myapp
      DATABASE_URL: postgresql+asyncpg://user:password@postgres:5432/myappdb
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: profile-pictures
    networks:
      - app-network
    ports:
      - "8000:8000" # Expose FastAPI on port 8000 of the host

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
    - ./nginx.conf:/etc/nginx.conf
    - ./default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - fastapi
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
    command: server /data
    volumes:
      - minio-data:/data
    networks:
      - app-network

  test:
    build: .
    command: pytest tests/test_upload_profile_pic.py
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - minio
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@postgres:5432/myappdb
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: profile-pictures
    networks:
      - app-network    

volumes:
  postgres-data:
  pgadmin-data:
  minio-data:

networks:
  app-network: